/*
 * FlickeringFirefly.cpp
 *
 *  Created on: April 12, 2016
 *      Author: davy
 */

#include "FastLED.h"
#include "FireflyLED.h"
#include "FlickeringFirefly.h"


/**************************************************************************/
/*!
    Constructor
*/
/**************************************************************************/
FlickeringFirefly::FlickeringFirefly(uint8_t pin) {
  init();
  blinkState = 0;
  setPin(pin);
}

/*========================================================================*/
/*                           PUBLIC FUNCTIONS                             */
/*========================================================================*/

/**************************************************************************/
/*!
    Update function that controls the Firefly behavior
*/
/**************************************************************************/
void FlickeringFirefly::update(void) {
  if (enabled) {

    // flickering generated by perlin algorithm
    blinkState = inoise8(millis());

    aWrite(blinkState);
  }
}

